<?php

declare(strict_types=1);

namespace Laventure\Component\Database\Drivers\Sqlite\Connection;

use Laventure\Component\Database\Configuration\Contract\ConfigurationInterface;
use Laventure\Component\Database\Connection\Extensions\PDO\Dsn\Builder\Factory\PdoDsnBuilderFactoryInterface;
use Laventure\Component\Database\Connection\Extensions\PDO\PdoConnection;
use Laventure\Component\Database\DatabaseInterface;
use Laventure\Component\Database\Drivers\DriverName;
use Laventure\Component\Database\Drivers\Sqlite\Query\Builder\SqliteQueryBuilder;
use Laventure\Component\Database\Drivers\Sqlite\Schema\Table\SqliteTable;
use Laventure\Component\Database\Drivers\Sqlite\SqliteDatabase;
use Laventure\Component\Database\Query\Builder\SQL\SQLQueryBuilderInterface;
use Laventure\Component\Database\Schema\Table\TableInterface;

/**
 * SqliteConnection
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Database\PdoConnection\Drivers\Sqlite
*/
class SqliteConnection extends PdoConnection
{
    /**
     * @inheritDoc
    */
    public function getName(): string
    {
        return DriverName::Sqlite;
    }




    /**
     * @inheritDoc
    */
    public function createQueryBuilder(): SQLQueryBuilderInterface
    {
        return new SqliteQueryBuilder($this->createPdoQueryBuilder());
    }




    /**
     * @inheritDoc
    */
    public function getDatabase(): DatabaseInterface
    {
        return new SqliteDatabase($this);
    }





    /**
     * @inheritDoc
    */
    public function table(string $name, string $schemaName = ''): TableInterface
    {
        return new SqliteTable($this, $name, $schemaName);
    }






    public function getPdoDsnBuilderFactory(): PdoDsnBuilderFactoryInterface
    {
        return parent::getPdoDsnBuilderFactory(); // TODO: Change the autogenerated stub
    }






    /**
     * @param ConfigurationInterface $config
     * @return string
    */
    private function makeSQLiteDsn(ConfigurationInterface $config): string
    {
        return sprintf('%s:%s', $config->required('driver'), $config->getDatabase());
    }
}
